import logging
import re
import secrets
import shutil
import subprocess as sp
from typing import Optional

from config import BaseConfig
from ..core.exceptions import MicroSamplerPCParsingError
from ..core.states import (
    MicroSamplerParseState,
    MicroSamplerSimulationState,
    MicroSamplerStatsState,
)
from ..pc_finder import find_pcs
from .defs import (
    MicroSamplerTCDeploymentState,
    MicroSamplerTCIterationResult,
    MicroSamplerTCLoopContext,
)
from .exceptions import BuildError, IllegalCodeError
from ...states import DeploymentState
from .struct import BuildResult

logger = logging.getLogger(__name__)


class MicroSamplerTCInitialState(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        run_config = ctx.context.run_config

        ctx.context.current_key_index = 0
        ctx.context.current_app_index = 0
        ctx.context.current_global_iteration = 0
        ctx.context.current_key_name = None
        ctx.context.current_key_file = None
        ctx.context.log_prefix = None
        ctx.context.pc_addresses = None
        ctx.context.collected_data.clear()

        # Keys are generated by MicroSamplerTCPrepareKeyStage.
        run_config.keys.clear()

        if len(run_config.apps) == 0:
            ctx.stop(ValueError("expected at least one application, found zero"))
            return

        if run_config.global_iterations <= 0:
            ctx.stop(
                ValueError(
                    "global_iterations must be greater than zero, "
                    f"found {run_config.global_iterations}"
                )
            )
            return

        self.append_deployment_state(
            ctx,
            MicroSamplerTCDeploymentState.PREPARE,
        )


class MicroSamplerTCPrepareState(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        ctx.context.current_global_iteration = 0
        self.append_deployment_state(ctx, MicroSamplerTCDeploymentState.HARNESS_VERIFY)


class MicroSamplerTCVerifyLegalCode(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        acceptable_references = set(self.config.harness.allowed_references)
        for m in re.finditer(r"#include \"(?P<filename>.*?)\"", ctx.context.implementation):
            if m.group("filename") not in acceptable_references:
                ctx.stop(IllegalCodeError(ctx.context.implementation))
                return
        self.append_deployment_state(ctx, MicroSamplerTCDeploymentState.HARNESS_PREPARE)


class MicroSamplerTCWriteAttack(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        file_name = self.config.harness.prefix / self.config.harness.target
        with open(file_name, mode='w+') as fp:
            fp.write(ctx.context.implementation)
        self.append_deployment_state(ctx, MicroSamplerTCDeploymentState.HARNESS_COMPILE)


class MicroSamplerTCCompileHarness(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        harness_prefix = self.config.harness.prefix
        logger.info(f"Building harness in: {harness_prefix}")
        logger.info(f"Fetching UUT source code...")
        shutil.copy(self.config.harness.uut.prefix / self.config.harness.uut.file, harness_prefix)
        logger.info("Building harness...")
        args = ["make", "clean", "harness", *self.config.harness.make_defines]
        logger.debug(f"running make with args: {args}")
        make_output = sp.run(
            args,
            capture_output=True,
            cwd=harness_prefix,
        )
        ctx.context.build_status = BuildResult(
            stdout=make_output.stdout.decode(),
            stderr=make_output.stderr.decode(),
            return_code=make_output.returncode,
        )
        if ctx.context.build_status.return_code != 0:
            ctx.stop(BuildError(ctx.context.build_status))
            return
        self.append_deployment_state(ctx, MicroSamplerTCDeploymentState.DEPLOYMENT_PREPARE)


class MicroSamplerTCPrepareKeyStage(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        run_config = ctx.context.run_config
        logger.info("Generating key file...")

        if run_config.key_size <= 0:
            ctx.stop(
                ValueError(
                    "key_size must be greater than zero, "
                    f"found {run_config.key_size}"
                )
            )
            return

        if run_config.fixed_key is not None:
            key_string = run_config.fixed_key.lower()
            if len(key_string) != run_config.key_size:
                ctx.stop(
                    ValueError(
                        "fixed_key length does not match key_size: "
                        f"expected {run_config.key_size}, "
                        f"found {len(key_string)}"
                    )
                )
                return
            if re.fullmatch(r"[0-9a-f]+", key_string) is None:
                ctx.stop(
                    ValueError(
                        "fixed_key must contain only hexadecimal characters"
                    )
                )
                return
        else:
            alphabet = "0123456789abcdef"
            key_string = "".join(
                secrets.choice(alphabet)
                for _ in range(run_config.key_size)
            )

        key_name = (
            f"{run_config.run_name}-"
            f"{ctx.context.current_global_iteration:04d}"
        )
        key_directory = self.config.microsampler.working_directory / "scripts" / "keys"
        key_directory.mkdir(parents=True, exist_ok=True)
        key_file = key_directory / f"{key_name}.key"
        logger.info("Saving key to %s", key_file)
        key_file.write_text(key_string, encoding="utf-8")

        # Core MicroSampler states select keys through run_config.keys and
        # current_key_index, so keep those fields synchronized with the key
        # generated by this custom deployment.
        run_config.keys[:] = [key_name]
        ctx.context.current_key_index = 0
        ctx.context.current_key_name = key_name
        ctx.context.current_key_file = key_file

        app = run_config.apps[ctx.context.current_app_index]
        ctx.context.log_prefix = (
            self.config.microsampler.deployment_prefix
            / "logs"
            / run_config.design
            / run_config.suite
            / app
            / str(run_config.iterations)
            / key_name
        )
        ctx.context.log_prefix.mkdir(parents=True, exist_ok=True)

        self.append_deployment_state(
            ctx,
            MicroSamplerTCDeploymentState.MICROSAMPLER_DEPLOYMENT,
        )


class MicroSamplerTCPrepareDeploymentStage(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        logger.info("Staging Deployment...")
        deploy_path = self.config.harness.deployment_prefix
        deploy_path.mkdir(parents=True, exist_ok=True)
        shutil.copy(self.config.harness.prefix / self.config.harness.executable, deploy_path)
        shutil.copy(self.config.harness.prefix / "build" / self.config.harness.assembly_file, deploy_path)
        ctx.context.run_config.executable = deploy_path / self.config.harness.executable
        self.append_deployment_state(ctx, MicroSamplerTCDeploymentState.KEY_PREPARE)


class MicroSamplerTCLoopControllerState(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        ctx.context.current_global_iteration += 1

        if ctx.context.current_global_iteration >= ctx.context.run_config.global_iterations:
            return

        self.append_deployment_state(ctx, MicroSamplerTCDeploymentState.KEY_PREPARE)


class MicroSamplerTCDeploymentStage(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        if ctx.context.pc_addresses is None:
            pc_config = ctx.context.run_config.pc_config

            if not pc_config.obj_file.is_file():
                ctx.stop(
                    FileNotFoundError(
                        "MicroSampler object dump was not found: "
                        f"{pc_config.obj_file}"
                    )
                )
                return

            pc_addresses = find_pcs(
                pc_config.obj_file,
                pc_config.roi_function,
                pc_config.uut_function,
                pc_config.warmup,
            )
            if pc_addresses is None:
                ctx.stop(MicroSamplerPCParsingError(pc_config))
                return

            ctx.context.pc_addresses = pc_addresses

        self.append_deployment_state(
            ctx,
            MicroSamplerTCDeploymentState.MICROSAMPLER_SIMULATION,
        )


class MicroSamplerTCSimulationStage(MicroSamplerSimulationState):
    def __init__(self, ctx: BaseConfig, sp_timeout: Optional[float] = None):
        super().__init__(ctx, sp_timeout, MicroSamplerTCDeploymentState.MICROSAMPLER_PARSE)


class MicroSamplerTCParseStage(MicroSamplerParseState):
    def __init__(self, ctx: BaseConfig, sp_timeout: Optional[float] = None):
        super().__init__(ctx, sp_timeout, MicroSamplerTCDeploymentState.MICROSAMPLER_STATS)


class MicroSamplerTCStatsStage(MicroSamplerStatsState):
    def __init__(self, ctx: BaseConfig, sp_timeout: Optional[float] = None):
        super().__init__(ctx, sp_timeout, MicroSamplerTCDeploymentState.DATA_COLLECTION)


class MicroSamplerTCDataCollectionStage(DeploymentState):
    def execute(self, ctx: MicroSamplerTCLoopContext):
        run_config = ctx.context.run_config
        log_prefix = ctx.context.log_prefix
        key_name = ctx.context.current_key_name
        key_file = ctx.context.current_key_file
        executable = run_config.executable

        if log_prefix is None:
            ctx.stop(RuntimeError("log_prefix was not prepared"))
            return
        if key_name is None or key_file is None:
            ctx.stop(RuntimeError("generated key information is missing"))
            return
        if executable is None:
            ctx.stop(RuntimeError("deployed executable path is missing"))
            return

        simulation_trace = log_prefix / "out-all-asm.log.gz"
        parsed_state = log_prefix / "uarch.pickle"
        sets_file = log_prefix / "sets.pickle"
        stats_output = log_prefix / f"stats-{run_config.phi}_{run_config.alpha}.log"
        simulation_log = log_prefix / "launch_simulation.log"
        parse_log = log_prefix / "launch_parse.log"
        stats_log = log_prefix / "launch_stats.log"

        required_files = [
            key_file,
            executable,
            simulation_trace,
            parsed_state,
            sets_file,
            stats_output,
            simulation_log,
            parse_log,
            stats_log,
        ]
        missing_files = [path for path in required_files if not path.is_file()]
        if missing_files:
            ctx.stop(
                FileNotFoundError(
                    "required deployment artifacts are missing: "
                    + ", ".join(str(path) for path in missing_files)
                )
            )
            return

        if not stats_output.read_text(
            encoding="utf-8",
            errors="replace",
        ).strip():
            ctx.stop(ValueError(f"stats output is empty: {stats_output}"))
            return

        ctx.context.collected_data.append(
            MicroSamplerTCIterationResult(
                global_iteration=ctx.context.current_global_iteration,
                key_name=key_name,
                key_file=key_file,
                executable=executable,
                log_prefix=log_prefix,
                simulation_trace=simulation_trace,
                parsed_state=parsed_state,
                sets_file=sets_file,
                stats_output=stats_output,
                simulation_log=simulation_log,
                parse_log=parse_log,
                stats_log=stats_log,
            )
        )

        self.append_deployment_state(
            ctx,
            MicroSamplerTCDeploymentState.LOOP_CHECK,
        )
