@startuml

object "Start"

object "Hypothesis Agent" {
Creates an experiment design to achieve the desired goal
}

object "Implementation Agent" {
Creates the test case code that is passed to the simulation
}

object "Summarization Agent" {
Summarizes the analysis results to further guide the next implementation\n\nCombines data from Analysis, Hypothesis, Implementation, and Analysis
}

object Simulation {
Runs the test case and outputs raw results
}

object Analysis {
Analyzes the raw results and produces statistics
}

Start --> Simulation : "1. First simulation with no attack\nto get a baseline"
Simulation -> Analysis : "2. Passes raw results to"
Analysis --> "Summarization Agent" : "4. Creates statistics data for"
"Summarization Agent" --> "Hypothesis Agent" : "5. Guides next experiment"
"Implementation Agent" <-- "Hypothesis Agent": "6. Guides implementation"
Simulation <-- "Implementation Agent" : "7. Designs code for"

"Implementation Agent" <.. Simulation : "Build failures"
Simulation ..> "Summarization Agent" : "Runtime errors"

object Conclusion {
The execution ends here
}

Conclusion <-- Analysis : "8. If early stopping criteria is met"

@enduml