#ifndef CONTEXT_H
#define CONTEXT_H

/*
This file contains the definitions for the contexts that will be passed to the client during execution.
trial_context_t contains the definition for the parameters that will be passed to the UUT, this will be pre-populated by the harness, but can be modified by the client later
global_context_t contains the definition of the global state, this can be modified by global_setup and global_teardown, but not in the trial_ functions.
bench_context_t contains the definition of the trial/iteration specific state, it also has a read-only copy of the global state, this cannot be modified, but the state member can be modified by the trial_ functions.
*/

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


typedef struct {
    uint32_t * const x;         // OUTPUT: result (and also initial base)
    uint32_t * const r;         // Precomputed constant (Montgomery-related)
    unsigned char * const e;    // exponent (e.g., RSA exponent)
    size_t elen;                // length of exponent in bytes
    uint32_t * const m;         // modulus
    uint32_t m0i;               // Montgomery constant (precomputed inverse)
    uint32_t * const t1;        // temp buffer
    uint32_t * const t2;        // temp buffer
} trial_context_t;

typedef struct {
    const int class;                // the class to classify (0, 1)
    const size_t iterations;        // the number of iterations the UUT will be run for
    void* state;                    // for use by the client, allows storing global state, can be read, but not modified during the test iterations
} global_context_t;

typedef struct {
    const global_context_t* const global_ctx;   // read-only global state may have user-defined state in the state variable
    const size_t iteration;                     // defines which iteration this is
    void* state;                                // modifiable bench state that can be modified during the iteration
} bench_context_t;


/// @brief Used by the harness to initialize the parameters to be passed to the UUT.
/// @param key The key generated by the client
/// @param iters The number of iterations used during the function execution
/// @return Returns an initialized struct that can be passed to the trial_ functions and the UUT.
trial_context_t create_default_trial_context(char* key, size_t iters);


/// @brief Used by the harness to initialize the global context
/// @param class the class to be classified
/// @param iterations the number of iterations to run the UUT for
/// @return a global context ready to be used by the client
global_context_t create_global_context(const int class, const size_t iterations);

/// @brief creates an iteration context for the client
/// @param global_ctx a read-only copy of the global context
/// @param iteration the current iteration
/// @return an iteration context ready to be used by the client
bench_context_t create_context(global_context_t* global_ctx, const size_t iteration);

#endif